# Generated by Django 3.1.2 on 2020-10-08 06:30

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name should contain minimum 3 characters')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email')])),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
