# Generated by Django 3.1.2 on 2020-10-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_auto_20201011_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
