# Generated by Django 3.1.2 on 2020-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_auto_20201009_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
