# Generated by Django 3.1.2 on 2020-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0007_auto_20201009_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
